services:
  app:
    image: assessment
    container_name: app
    build:
      context: .
      dockerfile: Assessment/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - shared_network
    environment:
      # TODO: manage actual secrets
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - shared_network
    environment:
      # TODO: manage actual secrets
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: # Persistent storage on host

networks:
  shared_network: # Shared network for communication between services
  